config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/programs', to: 'static_pages#programs'
  get  '/programs/mentoring', to: 'static_pages#mentoring'
  get '/signup', to: 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save {email.downcase!}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, length: {minimum: 6}, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def mentoring
  end

  def programs
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 about-us">
      <span name="about" ></span>
      <h3></h3>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12 underline">
      <hr>
    </div>
  </div>
</div>
<div class="row">
	<div class="container contact-us">
		<div class="col-xs-offset-2 col-xs-8 col-sm-offset-0 col-sm-6 col-md-3">
			<div class="footer-col">
				<h4 class="heading"><a href="#">Press</a></h4>
				<h4 class="heading"><a href="#">FAQs</a></h4>
				<h4 class="heading"><a href="#">Become a volunteer</a></h4>
				<h4 class="heading"><a href="#">Blog</a></h4>
				<h3 class="title-style-2"><span class="title-under"></span></h3>
			</div>
		</div>
		
		<div class="col-xs-offset-2 col-xs-8 col-sm-offset-0 col-sm-6 col-md-3">
			<div class="footer-col">
				<h4 class="heading">Ficksburg | Gauteng | Venda</h4>
				<h4>Paranormalminds Headquaters</h4>
				<h4>7500 Zone 8</h4>
				<h4>Free State, 9730</h4>
				<h3 class="title-style-2"><span class="title-under"></span></h3>
			</div>
		</div>
		
		<div class="clearfix visible-sm-block"></div>
		
		<div class="col-xs-offset-2 col-xs-8 col-sm-offset-0 col-sm-6 col-md-3">
			<div class="footer-col">
				<h4 class="heading">contact us</h4>
				<h4>info@paranormalminds.org</h4>
				<h4>cell:<a href="tel:+27603374561"> +27603374561</a></h4>
				<h4>cell:<a href="tel:+27603374561"> +27603374561</a></h4>
				<h3 class="title-style-2"><span class="title-under"></span></h3>
			</div>
		</div>
		<div class="col-xs-offset-2 col-xs-8 col-sm-offset-0 col-sm-6 col-md-3">
			<div class="footer-col">
				<h4><a href="#">tweeter</a></h4>
				<h4><a href="#">youtube</a></h4>
				<h4><a href="#">facebook</a></h4>
				<h4><a href="#">linkedin</a></h4>
				<h3 class="title-style-2"><span class="title-under"></span></h3>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="container social-media">
		<ul class="test">
			<li><a href="#"><i class="fa social-btn facebook-btn"></i></a></li>		
			<li><a href="#"><i class="fa social-btn twitter-btn"></i></a></li>		
			<li><a href="#"><i class="fa social-btn fa-github"></i></a></li>		
			<li><a href="#"><i class="fa social-btn linkedin-btn"></i></a></li>		
			<li><a href="#"><i class="fa social-btn fa-youtube"></i></a></li>		
		</ul>
	</div>
</div>
<footer class="footer">
  &copy; Paranormalminds
  <div>
    <a title="Privacy Policy" href="#">Privacy Policy</a>
    <a title="Terms of Service" href="#">Terms of Service</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-main">

  <div class="navbar-header">
  <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsemenu" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
    <a href = "<%= root_url %>"><img class="navbar-brand" src="<%= image_url('logo.png') %>" alt="logo">
    </a>
  </div>
  <div class="collapse navbar-collapse" id="collapsemenu">
    <div class="container">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "About", about_url ,'aria-haspoup' => 'true' %>
        </li>

        <li class="has-child">
          <%= link_to "Programs", programs_url ,'aria-haspoup' => 'true' %>
          <ul class="submenu">
            <li class="submenu-item">
              <%= link_to "Tutoring", root_url ,'aria-haspoup' => 'true' %>
            </li>

            <li class="submenu-item">
              <%= link_to "Mentoring", programs_mentoring_url ,'aria-haspoup' => 'true' %>
            </li>
            <li class="submenu-item">
              <%= link_to "Career Guidance", root_url ,'aria-haspoup' => 'true' %>
            </li>
            <li class="submenu-item">
              <%= link_to "Projects", root_url ,'aria-haspoup' => 'true' %>
            </li>
          </ul>
        </li>

        <li>
          <%= link_to "Careers", root_url ,'aria-haspoup' => 'true' %>
        </li>
        <li>
          <%= link_to "FAQ", root_url ,'aria-haspoup' => 'true' %>
        </li>
        <li class="active-button">
          <%= link_to "Sign in", root_url ,'aria-haspoup' => 'true' %>
        </li>
      </ul>
  </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="page-heading text-center">
    <div class="container-fliud zoomIn animated">
      <h3>ABOUT US <span class="title-under"></span></h3>
      <h4 class="page-description">
       It's all up to you to make your dreams viable.
      </h4>
      <h4 class="page-description">
        Our contribution is through <em>education</em>
      </h4>
    </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 about-us">
      <span name="about" ></span>
      <h3>The Paranormalminds Story</h3>

      <div class="container">
        <div class="row">
          <div class="col-md-12 underline">
            <hr>
          </div>
        </div>
      </div>

      <p>
        Paranormalminds was started by three undergraduates students who experienced the difficulties in surviving
        their first year in varsity. By the end of their first year, they decided to solve this problem.

        We offer learning resources to learners in high school from under-privileged background.
        Through our community platform, mentors, tutors, and other private qualified entities
        invest in tomorrow's leaders ensuring a brighter future for a black child.

        We dont believe in education, but the knowledge and skill one gets from it because <em>education is what
        remains after one has forgotten what one has learned in school.</em>
      </p>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12 about-us">
      <span name="about" ></span>
      <h3>Meet Our Team!</h3>
    </div>
  </div>
</div>

</div>
<div class="container">
  <div class="row">
    <div class="col-md-12 underline">
      <hr>
    </div>
  </div>
</div>

<div class="container">
  <div class="row profile-thumbnail">
    <div class="col-md-4 b1">
      <img class="img-responsive" src="<%= image_url('profiles/team-male-profile-holder.jpg') %>">
      <h4>Ncheeta Morero</h4>
      <h5>-COO- Asst. Director Operations </h5>
      <p>Mechanical Engineering at University of Witwatersrand.<br/></p>

      <h3 class="title-style-1"><span class="title-under"></span></h3>

      <ul>
        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter" ></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus-square"></i></a></li>
      </ul>
    </div>


    <div class="col-md-4">
      <img class="img-responsive" src="<%= image_url('profiles/team-male-profile-holder.jpg') %>">
      <h4>Wilson Makoae</h4>
      <h5>Founder and CEO</h5>
      <p>Mechanical Engineering at University of Witwatersrand.<br/></p>

      <h3 class="title-style-1"><span class="title-under"></span></h3>

      <ul>
        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter" ></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus-square"></i></a></li>
      </ul>
    </div>


    <div class="col-md-4 b3">
      <img class="img-responsive" src="<%= image_url('profiles/team-male-profile-holder.jpg') %>">
      <h4>Ndivho Maginya</h4>
      <h5>-CFO- Asst. Director Finance</h5>
      <p>Mechanical Engineering at University of Witwatersrand.<br/></p>

      <h3 class="title-style-1"><span class="title-under"></span></h3>

      <ul>
        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter" ></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus-square"></i></a></li>
      </ul>
    </div>
  </div>
</div>
<div class="container">
  <div class="row team">
    <div class="col-md-4 b1">
      <img class="img-responsive" src="<%= image_url('profiles/team-male-profile-holder.jpg') %>">
      <h4>Victor Qenehelo</h4>
      <h5>-COO- Asst. Director Marketing</h5>
      <p>Mechanical Engineering at University of Witwatersrand.<br/></p>

      <h3 class="title-style-1"><span class="title-under"></span></h3>

      <ul>
        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter" ></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus-square"></i></a></li>
      </ul>
    </div>

    <div class="col-md-4 b3">
      <img class="img-responsive" src="<%= image_url('profiles/team-female-profile-holder.jpg') %>">
      <h4>Rachel Monyai</h4>
      <h5>-COO- Asst. Director Finance</h5>
      <p>Finance in Accounting at University of Cape Town.<br/></p>

      <h3 class="title-style-1"><span class="title-under"></span></h3>

      <ul>
        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter" ></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus-square"></i></a></li>
      </ul>
    </div>

    <div class="col-md-4">
      <img class="img-responsive" src="<%= image_url('profiles/team-male-profile-holder.jpg') %>">
      <h4>Mbele Lebohang</h4>
      <h5>-COO- Asst. Director Development</h5>
      <p>Electrical and Computer Engineering at University of Cape Town.<br/></p>

      <h3 class="title-style-1"><span class="title-under"></span></h3>

      <ul>
        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter" ></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus-square"></i></a></li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12 about-us">
      <span name="about" ></span>
      <h3>What Learners Says About Us!</h3>
    </div>
  </div>
</div>

</div>
<div class="container">
  <div class="row">
    <div class="col-md-12 underline">
      <hr>
    </div>
  </div>
</div>

<div style="position: relative;">

  <div class="container">
    <div class="row learners">
      <div class="col-md-6">
        <div class="about1">
          <img class="pic1Ab" src="<%= image_url('profiles/female-profile-holder.jpg') %>">
          <h3>Lerato Mohautse, Tlotlisong Sec. School</h3>
          <p>If it hadn’t been for Paranormalminds, I wouldn’t have been able
            to apply to study at University of Cape Town...You’re a team full of smarts and hearts.
        </div>
      </div>

      <div class="col-md-6">
        <div class="about2">
          <img class="pic2Ab" src="<%= image_url('profiles/male-profile-holder.jpg') %>">
          <h3>Lehetla Lehetla, Marallaneng Sec. School</h3>
          <p>Paranormalminds is a reliable bungee that has helped me to take a plunge of higher education. </p>
        </div>
      </div>
    </div>
  </div>

  <div class="horL"></div>

  <div class="container">
    <div class="row learners">
      <div class="col-md-6">
        <div class="about1">
          <img class="pic1Ab" src="<%= image_url('profiles/male-profile-holder.jpg') %>">
          <h3>Thapelo Rasemetse, Tlotlisong Sec. School</h3>
          <p>Becoming successful from an under privileged background is only half the story, Paranormalminds is the other half.</p>
        </div>
      </div>

      <div class="col-md-6">
        <div class="about2">
          <img class="pic2Ab" src="<%= image_url('profiles/female-profile-holder.jpg') %>">
          <h3>Thakane Thabana, Marallaneng Sec. School</h3>
          <p>Paranormalminds has changed my life by giving me the information i wouldn't
            ordinarily be able to access easily.</p>
        </div>
      </div>

    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12 about-us">
      <span name="about" ></span>
      <h3>Careers!</h3>
    </div>
  </div>
</div>

</div>
<div class="container">
  <div class="row">
    <div class="col-md-12 underline">
      <hr>
    </div>
  </div>
</div>
<div class="row">
  <div class=" container careers">
    <p>We want to change the way learners think about education and learning.</p>
    <p>Visit our Careers page to view our open positions or to submit your CV for general consideration.</p>
    <a class="btn" title="Join the team" href="#">Join the team</a>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>Life is too short, build things that matter.</h1>

<h2>
  This is the home page for the
  <a href="http://www.railstutorial.org/">Paranormalminds</a>
  test application.
</h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>

app/views/static_pages/mentoring.html.erb
<% provide(:title, "Mentoring") %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 about-us">
      <span name="about" ></span>
      <h3>Paranormalminds Mentoring Program</h3>

      <div class="container">
        <div class="row">
          <div class="col-md-12 underline">
            <hr>
          </div>
        </div>
      </div>

      <p>
        Paranormalminds was started by three undergraduates students who experienced the difficulties in surviving
        their first year in varsity. By the end of their first year, they decided to solve this problem.

        We offer learning resources to learners in high school from under-privileged background.
        Through our community platform, mentors, tutors, and other private qualified entities
        invest in tomorrow's leaders ensuring a brighter future for a black child.

        We dont believe in education, but the knowledge and skill one gets from it because <em>education is what
        remains after one has forgotten what one has learned in school.</em>

        At Paranormalminds we believe that a good mentoring relationship can provide learners with someone that will
        share their professional knowledge and expertise in the field. Our mentors are available to answer any questions
        relevant to their careers or anything related to school. Good mentor-mentee relationships are a two way street;
        consequently, if you want a good relationship with your mentor, become a good mentee. This requires a genuine
        interest in your mentor and a willingness to do what it takes to become successful as a learner in your career.
      </p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12 about-us">
      <span name="about" ></span>
      <h3>Meet Our Mentors!</h3>
    </div>
  </div>
</div>

</div>
<div class="container">
  <div class="row">
    <div class="col-md-12 underline">
      <hr>
    </div>
  </div>
</div>


<div class="mentors">
  <div class="row profile-thumbnail ">
    <div class="col-md-4 b1">
      <img class="img-responsive" src="<%= image_url('profiles/team-female-profile-holder.jpg') %>">
      <h4>Nthabiseng Khomo</h4>
      <h5>-BSc. Biochemistry-</h5>
      <h5>University of Cape Town<br/></h5>
    </div>

    <div class="col-md-4">
      <img class="img-responsive" src="<%= image_url('profiles/team-male-profile-holder.jpg') %>">
      <h4>Lesedi Radebe</h4>
      <h5>-BEd. in Sinior and FET Teaching-</h5>
      <h5>University of Free State<br/></h5>
    </div>

    <div class="col-md-4 b3">
      <img class="img-responsive" src="<%= image_url('profiles/team-female-profile-holder.jpg') %>">
      <h4>Pontsho Fokothi</h4>
      <h5>--BSc. in Radiography--</h5>
      <h5>Central University of Technology<br/></h5>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-12 about-us">
      <span name="about" ></span>
      <h3>Become A Mentor!</h3>
    </div>
  </div>
</div>

</div>
<div class="container">
  <div class="row">
    <div class="col-md-12 underline">
      <hr>
    </div>
  </div>
</div>

<div class="row">
  <div class=" container careers">
    <p>
      Are you willingness to share your skills, knowledge, and expertise? Do you values ongoing learning and growth in
      your field?
    </p>
    <p>At Paranormalminds you can give back to your community by becoming a mentor to our community of learners.</p>
    <a class="btn" title="become-a-mentor" href="#">Become a mentor</a>
  </div>
</div>

app/views/static_pages/programs.html.erb
<% provide(:title, "Programs") %>

<div class="page-heading text-center">
  <div class="container-fliud zoomIn animated">
    <h3>PROGRAMS<span class="title-under"></span></h3>
    <h4 class="page-description">
      A route to success.
    </h4>
    <h4 class="page-description">
      We synthesize you around your <em>strengths</em>.
    </h4>
  </div>
</div>

<h3><%= link_to "Mentoring", programs_mentoring_path %></h3>
<h3><%= link_to "Tutoring", programs_mentoring_path %></h3>
<h3><%= link_to "Career guidance", programs_mentoring_path %></h3>
<h3><%= link_to "Beyond Class Room", programs_mentoring_path %></h3>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>